-- Create a table for payments
create table if not exists payments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  transaction_id text,
  amount numeric,
  method text default 'Pago Móvil',
  status text default 'pending'
);

-- Enable RLS (Security)
alter table payments enable row level security;

-- Allow anyone to insert (since we have no auth yet and want anonymous payments)
create policy "Enable insert for all users" on payments for insert with check (true);

-- Allow admins (service role) to read everything
-- (By default, no one can read without a policy)
